# more compatible for lower glibc
FROM golang:1.25-alpine

# Install build dependencies
RUN apk add --no-cache gcc g++ libstdc++

# Set working directory
WORKDIR /app

# Default command (can be overridden)
CMD ["bash"]