
FROM golang:1.25-bookworm

# Install build dependencies
RUN apt install -y g++ libstdc++-dev

# Set working directory
WORKDIR /app

# Default command (can be overridden)
CMD ["bash"]

# docker build -t golang-cpp:1.25-bookworm -f Dockerfile-bookworm.build .
