
FROM golang:1.25-bookworm

# Install build dependencies
RUN apt update && apt install -y g++ libstdc++-dev

# Set working directory
WORKDIR /app

# Default command (can be overridden)
CMD ["bash"]

# docker build -t go-cpp-builder:1.25 -f Dockerfile.build .
# docker run --rm -v "$(pwd)":/app go-cpp-builder:1.25 sh -c 'go build -ldflags "-s -w" -o dist/main main.go'